## Домашнє завдання:  Матриці і вектори (вступ до лін. алгебри)

In [47]:
import numpy as np
import random

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


##### 1.1 Створення вектору

Створення вектору за допомогою опції 1 (генерація випадкових чисел з модулем random.uniform):

Створення вектору рядка:

In [48]:
u = np.array([random.uniform(0, 1) for _ in range(10)])
u, u.shape

(array([0.83662341, 0.8868995 , 0.99742752, 0.68754829, 0.3916487 ,
        0.20481268, 0.20425515, 0.41157767, 0.80131783, 0.69459096]),
 (10,))

Створення вектору стовпця:

In [49]:
v = np.array([[random.uniform(0, 1)] for _ in range(10)])
v, v.shape

(array([[0.75375142],
        [0.96465393],
        [0.18209441],
        [0.17454076],
        [0.93480486],
        [0.00201433],
        [0.24277764],
        [0.06570891],
        [0.97329483],
        [0.26165012]]),
 (10, 1))

Створення вектору за допомогою опції 2 (генерація випадкових чисел з модулем random.uniform):

Створення вектору рядка:

In [50]:
u = np.random.rand(10)
u, u.shape

(array([0.93444183, 0.81287804, 0.04867243, 0.08870571, 0.70598154,
        0.815118  , 0.38508033, 0.86976379, 0.51398228, 0.26528863]),
 (10,))

Створення вектору стовпця:

In [51]:
v = np.random.rand(10, 1)
v, v.shape

(array([[0.77964287],
        [0.13384366],
        [0.47305861],
        [0.89870243],
        [0.14347272],
        [0.80941237],
        [0.65017959],
        [0.29173208],
        [0.39466199],
        [0.01067724]]),
 (10, 1))

#### 1.2 Створення матриці

In [52]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [53]:
print(
    f"Матриця:\n"
    f"{matrix}\n"
    f"Розміри матриці: {matrix.shape}\n"
    f"\n"
    f"Вектор рядок (u):\n"
    f"{u}\n"
    f"Розміри: {u.shape}\n"
    f"\n"
    f"Вектор стовпець (v):\n"
    f"{v}\n"
    f"Розміри: {v.shape}\n"
)


Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розміри матриці: (3, 3)

Вектор рядок (u):
[0.93444183 0.81287804 0.04867243 0.08870571 0.70598154 0.815118
 0.38508033 0.86976379 0.51398228 0.26528863]
Розміри: (10,)

Вектор стовпець (v):
[[0.77964287]
 [0.13384366]
 [0.47305861]
 [0.89870243]
 [0.14347272]
 [0.80941237]
 [0.65017959]
 [0.29173208]
 [0.39466199]
 [0.01067724]]
Розміри: (10, 1)



**ПРИМІТКА**

Замість запропонованого імені `vector` використовую ім'я змінної `u`, так як розглядаю додатково ще вектор-стовпець `v`.


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


Далі для зручності я взяла лише векор u (вектор-рядок).

#### 2.1 Додавання до вектора значення 10 та округлення значень

In [54]:
u

array([0.93444183, 0.81287804, 0.04867243, 0.08870571, 0.70598154,
       0.815118  , 0.38508033, 0.86976379, 0.51398228, 0.26528863])

In [56]:
u = np.round(u + 10, 2)
u

array([10.93, 10.81, 10.05, 10.09, 10.71, 10.82, 10.39, 10.87, 10.51,
       10.27])

#### 2.2 Домноження матриці на 2

In [58]:
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [57]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

#### 2.3 Створення нового вектору, який містить квадрат кожного vector

In [61]:
squared_u = np.square(u)
squared_u

array([119.4649, 116.8561, 101.0025, 101.8081, 114.7041, 117.0724,
       107.9521, 118.1569, 110.4601, 105.4729])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [62]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

#### 3.1 Множення матриць  $A$ та $B$ так, щоб результуюча матриця $R$ мала розмірність $(2 \times 2)$

In [68]:
result_matrix = B.dot(A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Отримано результуючу матрицю розміром $(2 \times 2)$. Щоб отрмати матрицю розмірністю $(2 \times 2)$, необхідно виконати множення саме матриці $B_{2 \times 3}$ на матрицю $A_{3 \times 2}$.

$R_{2 \times 2} = B_{2 \times 3}A_{3 \times 2}$

#### 3.2 Множення вектору $С$ на результуючу множення $R$

У результаті множення матриць $A_{3 \times 2}$ та матриці $B_{2 \times 3}$, так щоб результуюча матриця була розмірнісью $(2 \times 2)$, було виконано множення $B_{2 \times 3}A_{3 \times 2}$.

Нехай матриця $R$ результуюча для множення $B$ $A$. Тоді $R_{2 \times 2} = B_{2 \times 3}A_{3 \times 2}$.

Нехай матриця $N$ результуюча для множення $R$ $C$.

Якщо домножемо $R_{2 \times 2}$ на $C_{2 \times 1}$ отримаємо матрицю $N$ розмірністю $(2 \times 1)$.



In [72]:
N = result_matrix.dot(C)
N, N.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

Виконавши множення можемо впевнетись, що розмірність отриманої матриці $N$ після множення $R_{2 \times 2}$ на $C_{2 \times 1}$ - $(2 \times 1)$.

Отже  $N_{2 \times 1} = R_{2 \times 2} C_{2 \times 1}$.

#### 3.3 Множення матриці $D$ на  результуючу множення матриць $R$

Результуюча множення має розмірність $({2 \times 2})$ - $R_{2 \times 2}$

$R_{2 \times 2} = B_{2 \times 3}A_{3 \times 2}$

Нехай матриця $P$ результуюча для множення $RD$.

Тоді матриця $P$ буде мати розмірність $({2 \times 2})$

$P_{2 \times 2} = R_{2 \times 2} D_{2 \times 2}$

In [73]:
P = result_matrix.dot(D)
P, P.shape

(array([[0.5202, 0.7281],
        [0.2846, 0.2034]]),
 (2, 2))

Виконавши множення можемо впевнетись, що розмірність отриманої матриці $P$ після множення $R_{2 \times 2}$ на $D_{2 \times 2}$ - $(2 \times 2)$.

Отже  $P_{2 \times 2} = R_{2 \times 2} D_{2 \times 2}$.



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




#### 4.1 Транспонування результючої матриці $R$

In [75]:
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [79]:
R_T = result_matrix.T
R_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

Отримано трансаоновану матрицю $R^T$

#### 4.2 Транспонування вектору

In [84]:
u, u.shape

(array([10.93, 10.81, 10.05, 10.09, 10.71, 10.82, 10.39, 10.87, 10.51,
        10.27]),
 (10,))

In [85]:
u_T = u.T
u_T, u_T.shape

(array([10.93, 10.81, 10.05, 10.09, 10.71, 10.82, 10.39, 10.87, 10.51,
        10.27]),
 (10,))

Спробувавши застовувати транспонування до вектору рядка, бачимо, що дана спроба не змінила вигляду вектору.

In [86]:
v, v.shape

(array([[0.77964287],
        [0.13384366],
        [0.47305861],
        [0.89870243],
        [0.14347272],
        [0.80941237],
        [0.65017959],
        [0.29173208],
        [0.39466199],
        [0.01067724]]),
 (10, 1))

In [87]:
v_T = v.T
v_T, v_T.shape

(array([[0.77964287, 0.13384366, 0.47305861, 0.89870243, 0.14347272,
         0.80941237, 0.65017959, 0.29173208, 0.39466199, 0.01067724]]),
 (1, 10))

Спробувавши застовувати транспонування до вектору стовпця, бачимо, вектор змінив свій вигляд.

#### 4.3 Використання операції `numpy.expand_dims` над вектором `vector` з аргументом axis=1.

In [90]:
u, u.shape

(array([10.93, 10.81, 10.05, 10.09, 10.71, 10.82, 10.39, 10.87, 10.51,
        10.27]),
 (10,))

In [94]:
column_vector = np.expand_dims(u, axis=1)
column_vector, column_vector.shape

(array([[10.93],
        [10.81],
        [10.05],
        [10.09],
        [10.71],
        [10.82],
        [10.39],
        [10.87],
        [10.51],
        [10.27]]),
 (10, 1))

Бачимо, що застосування операції numpy.expand_dims над вектором-рядком додало нову вимірність, перетворюючи вектор з форми $(10,)$ на $(10, 1)$, що робить з вектора-рядка вектор-стовпець.

#### 4.4 Транспонування `column_vector`

In [95]:
column_vector_T = column_vector.T
column_vector_T, column_vector_T.shape

(array([[10.93, 10.81, 10.05, 10.09, 10.71, 10.82, 10.39, 10.87, 10.51,
         10.27]]),
 (1, 10))

Бачимо, що застосувавши транспонування, вектор-стовбець змінив свій вигляд, та перетворився на верктор-рядок, тобто розмірність змінилась з $(10, 1)$ на $(1, 10)$